---
driver:
  name: terraform
  variables:
    environment: test

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      controls:
        - url_check

platforms:
  - name: terraform

suites:
  - name: default
